version: '3.7'
volumes:
  database:
services:
  db:
    image: mariadb:latest
    container_name: database-mariadb
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=database
      - MYSQL_DATABASE=database
      - MYSQL_USER=database
      - MYSQL_PASSWORD=database
